version: '3'

services:
  db:
    image: mongodb
    env_file:
      - .env
  web_app:
    build:
      dockerfile: sentense_similarity/Dockerfile
      context: sentense_similarity
    image: sentense-similarity
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"