version: '3'

services:
  db:
    image: mongo:4.0.4
    env_file:
      - ../.env
  web_app:
    build:
      dockerfile: Dockerfile
      context: ./backend
    image: sentence-similarity
    env_file:
      - ../.env
    depends_on:
      - db
    ports:
      - 8000:8000